/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *
 * WARNING:
 * This project is a placeholder snapshot and is NOT the active firmware target.
 * Do not flash artifacts from `covapsy_usb_v1`.
 * Use `cubeide_project/covapsy_usb1` for all build/flash operations.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#warning "covapsy_usb_v1 is a placeholder project; build/flash covapsy_usb1 instead."

int main(void)
{
    /* Loop forever */
	for(;;);
}
